services:
  mongo:
    image: mongo:7.0
    container_name: solehex-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: solehex-app
    depends_on:
      - mongo
    ports:
      - '127.0.0.1:3001:5001'
    env_file:
      - .env
    volumes:
      - ./server/uploads:/app/server/uploads
    restart: unless-stopped

volumes:
  mongo-data:
